# Generated by Django 6.0.5 on 2026-05-08 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Device Name')),
                ('device_type', models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator'), ('gateway', 'Gateway'), ('camera', 'Camera'), ('controller', 'Controller'), ('other', 'Other')], default='sensor', max_length=50, verbose_name='Device Type')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Location')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='offline', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_used', models.TextField(verbose_name='Prompt Used')),
                ('result', models.TextField(verbose_name='Analysis Result')),
                ('anomalies_detected', models.BooleanField(default=False, verbose_name='Anomalies Detected')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Analyzed At')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='devices.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='Metric Name')),
                ('value', models.FloatField(verbose_name='Value')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='devices.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device Metric',
                'verbose_name_plural': 'Device Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
