# Generated by Django 4.2.16 on 2026-06-13 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Scores'),
        ),
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='PCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(default=dict, verbose_name='Collected Stats')),
                ('result', models.TextField(verbose_name='Analysis Result')),
                ('scores', models.JSONField(blank=True, default=dict, verbose_name='Scores')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Analyzed At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'PC Analysis',
                'verbose_name_plural': 'PC Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
